---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa-deplyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santa
  template:
    metadata:
        labels:
          app: santa
    spec:
      containers:
        - name: santa
          image: sharon111edapal/santa:$BUILD_ID

---

apiVersion: v1
kind: Service
metadata:
  name: santa-service
spec:
  type: NodePort
  selector:
    #    matchLabels:
      app: santa
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30303
